//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package nu.xom;

import java.io.Writer;

class Latin9Writer extends TextWriter {
    Latin9Writer(Writer var1, String var2) {
        super(var1, var2);
    }

    boolean needsEscaping(char var1) {
        if (var1 <= 163) {
            return false;
        } else if (var1 == 8364) {
            return false;
        } else {
            switch(var1) {
                case '¥':
                    return false;
                case '¦':
                    return true;
                case '§':
                    return false;
                case '¨':
                    return true;
                case '©':
                    return false;
                case 'ª':
                    return false;
                case '«':
                    return false;
                case '¬':
                    return false;
                case '\u00ad':
                    return false;
                case '®':
                    return false;
                case '¯':
                    return false;
                case '°':
                    return false;
                case '±':
                    return false;
                case '²':
                    return false;
                case '³':
                    return false;
                case '´':
                    return true;
                case 'µ':
                    return false;
                case '¶':
                    return false;
                case '·':
                    return false;
                case '¸':
                    return true;
                case '¹':
                    return false;
                case 'º':
                    return false;
                case '»':
                    return false;
                case '¼':
                    return true;
                case '½':
                    return true;
                case '¾':
                    return true;
                case '¿':
                    return false;
                case 'À':
                    return false;
                case 'Á':
                    return false;
                case 'Â':
                    return false;
                case 'Ã':
                    return false;
                case 'Ä':
                    return false;
                case 'Å':
                    return false;
                case 'Æ':
                    return false;
                case 'Ç':
                    return false;
                case 'È':
                    return false;
                case 'É':
                    return false;
                case 'Ê':
                    return false;
                case 'Ë':
                    return false;
                case 'Ì':
                    return false;
                case 'Í':
                    return false;
                case 'Î':
                    return false;
                case 'Ï':
                    return false;
                case 'Ð':
                    return false;
                case 'Ñ':
                    return false;
                case 'Ò':
                    return false;
                case 'Ó':
                    return false;
                case 'Ô':
                    return false;
                case 'Õ':
                    return false;
                case 'Ö':
                    return false;
                case '×':
                    return false;
                case 'Ø':
                    return false;
                case 'Ù':
                    return false;
                case 'Ú':
                    return false;
                case 'Û':
                    return false;
                case 'Ü':
                    return false;
                case 'Ý':
                    return false;
                case 'Þ':
                    return false;
                case 'ß':
                    return false;
                case 'à':
                    return false;
                case 'á':
                    return false;
                case 'â':
                    return false;
                case 'ã':
                    return false;
                case 'ä':
                    return false;
                case 'å':
                    return false;
                case 'æ':
                    return false;
                case 'ç':
                    return false;
                case 'è':
                    return false;
                case 'é':
                    return false;
                case 'ê':
                    return false;
                case 'ë':
                    return false;
                case 'ì':
                    return false;
                case 'í':
                    return false;
                case 'î':
                    return false;
                case 'ï':
                    return false;
                case 'ð':
                    return false;
                case 'ñ':
                    return false;
                case 'ò':
                    return false;
                case 'ó':
                    return false;
                case 'ô':
                    return false;
                case 'õ':
                    return false;
                case 'ö':
                    return false;
                case '÷':
                    return false;
                case 'ø':
                    return false;
                case 'ù':
                    return false;
                case 'ú':
                    return false;
                case 'û':
                    return false;
                case 'ü':
                    return false;
                case 'ý':
                    return false;
                case 'þ':
                    return false;
                case 'ÿ':
                    return false;
                default:
                    switch(var1) {
                        case 'Œ':
                            return false;
                        case 'œ':
                            return false;
                        case 'Ŕ':
                            return true;
                        case 'ŕ':
                            return true;
                        case 'Ŗ':
                            return true;
                        case 'ŗ':
                            return true;
                        case 'Ř':
                            return true;
                        case 'ř':
                            return true;
                        case 'Ś':
                            return true;
                        case 'ś':
                            return true;
                        case 'Ŝ':
                            return true;
                        case 'ŝ':
                            return true;
                        case 'Ş':
                            return true;
                        case 'ş':
                            return true;
                        case 'Š':
                            return false;
                        case 'š':
                            return false;
                        case 'Ţ':
                            return true;
                        case 'ţ':
                            return true;
                        case 'Ť':
                            return true;
                        case 'ť':
                            return true;
                        case 'Ŧ':
                            return true;
                        case 'ŧ':
                            return true;
                        case 'Ũ':
                            return true;
                        case 'ũ':
                            return true;
                        case 'Ū':
                            return true;
                        case 'ū':
                            return true;
                        case 'Ŭ':
                            return true;
                        case 'ŭ':
                            return true;
                        case 'Ů':
                            return true;
                        case 'ů':
                            return true;
                        case 'Ű':
                            return true;
                        case 'ű':
                            return true;
                        case 'Ų':
                            return true;
                        case 'ų':
                            return true;
                        case 'Ŵ':
                            return true;
                        case 'ŵ':
                            return true;
                        case 'Ŷ':
                            return true;
                        case 'ŷ':
                            return true;
                        case 'Ÿ':
                            return false;
                        case 'Ź':
                        case 'ź':
                        case 'Ż':
                        case 'ż':
                        default:
                            return true;
                        case 'Ž':
                            return false;
                        case 'ž':
                            return false;
                    }
            }
        }
    }
}
