//
// Source code recreated from a .class file by IntelliJ IDEA
// (powered by Fernflower decompiler)
//

package nu.xom;

import java.io.Writer;

class Latin5Writer extends nu.xom.TextWriter {
    Latin5Writer(Writer var1, String var2) {
        super(var1, var2);
    }

    boolean needsEscaping(char var1) {
        if (var1 <= 207) {
            return false;
        } else {
            switch(var1) {
                case 'Ð':
                    return true;
                case 'Ñ':
                    return false;
                case 'Ò':
                    return false;
                case 'Ó':
                    return false;
                case 'Ô':
                    return false;
                case 'Õ':
                    return false;
                case 'Ö':
                    return false;
                case '×':
                    return false;
                case 'Ø':
                    return false;
                case 'Ù':
                    return false;
                case 'Ú':
                    return false;
                case 'Û':
                    return false;
                case 'Ü':
                    return false;
                case 'Ý':
                    return true;
                case 'Þ':
                    return true;
                case 'ß':
                    return false;
                case 'à':
                    return false;
                case 'á':
                    return false;
                case 'â':
                    return false;
                case 'ã':
                    return false;
                case 'ä':
                    return false;
                case 'å':
                    return false;
                case 'æ':
                    return false;
                case 'ç':
                    return false;
                case 'è':
                    return false;
                case 'é':
                    return false;
                case 'ê':
                    return false;
                case 'ë':
                    return false;
                case 'ì':
                    return false;
                case 'í':
                    return false;
                case 'î':
                    return false;
                case 'ï':
                    return false;
                case 'ð':
                    return true;
                case 'ñ':
                    return false;
                case 'ò':
                    return false;
                case 'ó':
                    return false;
                case 'ô':
                    return false;
                case 'õ':
                    return false;
                case 'ö':
                    return false;
                case '÷':
                    return false;
                case 'ø':
                    return false;
                case 'ù':
                    return false;
                case 'ú':
                    return false;
                case 'û':
                    return false;
                case 'ü':
                    return false;
                case 'ý':
                    return true;
                case 'þ':
                    return true;
                case 'ÿ':
                    return false;
                case 'Ā':
                    return true;
                case 'ā':
                    return true;
                case 'Ă':
                    return true;
                case 'ă':
                    return true;
                case 'Ą':
                    return true;
                case 'ą':
                    return true;
                case 'Ć':
                    return true;
                case 'ć':
                    return true;
                case 'Ĉ':
                    return true;
                case 'ĉ':
                    return true;
                case 'Ċ':
                    return true;
                case 'ċ':
                    return true;
                case 'Č':
                    return true;
                case 'č':
                    return true;
                case 'Ď':
                    return true;
                case 'ď':
                    return true;
                case 'Đ':
                    return true;
                case 'đ':
                    return true;
                case 'Ē':
                    return true;
                case 'ē':
                    return true;
                case 'Ĕ':
                    return true;
                case 'ĕ':
                    return true;
                case 'Ė':
                    return true;
                case 'ė':
                    return true;
                case 'Ę':
                    return true;
                case 'ę':
                    return true;
                case 'Ě':
                    return true;
                case 'ě':
                    return true;
                case 'Ĝ':
                    return true;
                case 'ĝ':
                    return true;
                case 'Ğ':
                    return false;
                case 'ğ':
                    return false;
                case 'Ġ':
                    return true;
                case 'ġ':
                    return true;
                case 'Ģ':
                    return true;
                case 'ģ':
                    return true;
                case 'Ĥ':
                    return true;
                case 'ĥ':
                    return true;
                case 'Ħ':
                    return true;
                case 'ħ':
                    return true;
                case 'Ĩ':
                    return true;
                case 'ĩ':
                    return true;
                case 'Ī':
                    return true;
                case 'ī':
                    return true;
                case 'Ĭ':
                    return true;
                case 'ĭ':
                    return true;
                case 'Į':
                    return true;
                case 'į':
                    return true;
                case 'İ':
                    return false;
                case 'ı':
                    return false;
                case 'Ĳ':
                    return true;
                case 'ĳ':
                    return true;
                case 'Ĵ':
                    return true;
                case 'ĵ':
                    return true;
                case 'Ķ':
                    return true;
                case 'ķ':
                    return true;
                case 'ĸ':
                    return true;
                case 'Ĺ':
                    return true;
                case 'ĺ':
                    return true;
                case 'Ļ':
                    return true;
                case 'ļ':
                    return true;
                case 'Ľ':
                    return true;
                case 'ľ':
                    return true;
                case 'Ŀ':
                    return true;
                case 'ŀ':
                    return true;
                case 'Ł':
                    return true;
                case 'ł':
                    return true;
                case 'Ń':
                    return true;
                case 'ń':
                    return true;
                case 'Ņ':
                    return true;
                case 'ņ':
                    return true;
                case 'Ň':
                    return true;
                case 'ň':
                    return true;
                case 'ŉ':
                    return true;
                case 'Ŋ':
                    return true;
                case 'ŋ':
                    return true;
                case 'Ō':
                    return true;
                case 'ō':
                    return true;
                case 'Ŏ':
                    return true;
                case 'ŏ':
                    return true;
                case 'Ő':
                    return true;
                case 'ő':
                    return true;
                case 'Œ':
                    return true;
                case 'œ':
                    return true;
                case 'Ŕ':
                    return true;
                case 'ŕ':
                    return true;
                case 'Ŗ':
                    return true;
                case 'ŗ':
                    return true;
                case 'Ř':
                    return true;
                case 'ř':
                    return true;
                case 'Ś':
                    return true;
                case 'ś':
                    return true;
                case 'Ŝ':
                    return true;
                case 'ŝ':
                    return true;
                case 'Ş':
                    return false;
                case 'ş':
                    return false;
                default:
                    return true;
            }
        }
    }
}
